import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  NAV from "@/components/custom/nav"
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white text-black")}>
        <div>
          <div >

          <NAV />
          </div>
          <div className="p-[130px] w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
