import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  NAV from "@/app/home/page"
import Footer from "@/components/custom/footer"
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white text-black")}>
        <div>
          

          
          <div className=" w-full">{children}</div>
          
          <Footer />
          
        </div>
      </body>
    </html>
  );
}
